server:
  port: 9090

spring:
  application:
    #不要用下划线
    name: web-consumer
  mvc:
    #静态资源的访问
    static-path-pattern: /static/**
  thymeleaf:
    #不使用页面缓存
    cache: false
    #访问thymeleaf模板页面的路径前缀
    prefix: classpath:/templates/
    #访问thymeleaf模板页面的路径后缀
    suffix: .html
    #使用的文件类型
    mode: HTML5
    #文件的字符编码
    encoding: UTF-8
    servlet:
      #文件的内容类型
      content-type: text/html
  #配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db5?useSSL=false&characterEncoding=utf8
    username: root
    password: 19960701
    # 连接池的配置信息
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL

eureka:
  #客户端
  client:
    service-url:
      #注册到注册中心的路径（功能模块可以同时注册到多个注册中心，至少要注册一个）
      defaultZone: http://127.0.0.1:8086/eureka